namespace BookStore.SemanticSearch.Application.Search.DTOs;

/// <summary>
/// A single semantic search result with similarity score.
/// </summary>
/// <param name="BookId">The book identifier.</param>
/// <param name="Title">Title of the book.</param>
/// <param name="Author">Author name.</param>
/// <param name="Description">Short content description.</param>
/// <param name="SimilarityScore">Cosine similarity score (0 to 1, higher is more similar).</param>
public sealed record SemanticSearchResultDto(
    Guid BookId,
    string Title,
    string Author,
    string Description,
    double SimilarityScore);

/// <summary>
/// Full response from semantic search, including optional LLM summary.
/// </summary>
/// <param name="Results">The ranked search results.</param>
/// <param name="LlmSummary">Optional natural language summary generated by the LLM, or null.</param>
public sealed record SemanticSearchResponse(
    IReadOnlyList<SemanticSearchResultDto> Results,
    string? LlmSummary);
